"""
synthetic_data.py — NEXPIRE Model A
=====================================
Synthetic training data generator.

!! IMPORTANT: ALL DATA GENERATED BY THIS MODULE IS SYNTHETIC !!
   It is generated from hand-crafted statistical distributions and
   does NOT represent real retailer sales, actual demand, or real
   inventory data. This module exists solely to bootstrap the model
   before real feed integration.

   When real retailer data is available, replace the call to
   generate_synthetic_dataset() in train_model.py with your real
   data loader — the interface (column names, types) must remain the same.

Generation philosophy:
  - Per-category shelf-life distributions match category_shelf_life.json.
  - Per-category price-elasticity curves with realistic noise.
  - Simulated weather correlation (hot days → more beverage/fresh produce demand,
    rain → less foot traffic, weekends → higher foot traffic).
  - Time-indexed rows (date column) to enable time-based train/test split.
  - Reproducible via fixed random seed (default: 42).
  - Distribution choices documented in docstrings inline.

Columns produced (16 features + target):
  date, category, sku_id, store_id,
  urgency_score,                        # engineered from days_to_expiry
  days_to_expiry,                       # raw (kept for audit; NOT fed to model)
  current_price, cost_price,
  qty_on_hand,
  avg_daily_velocity_7d, avg_daily_velocity_28d,
  temperature_today, precip_probability,
  is_weekend, is_holiday, hour_of_day,
  store_foot_traffic_index,
  past_discount_depth, past_sellthrough_rate,
  local_demand_score,
  b2b_flag,
  cat_x_temp,                           # interaction: category weather sensitivity × temperature
  cat_x_precip,                         # interaction: category weather sensitivity × precip
  sell_probability                      # TARGET: P(sold within remaining window at current price)
"""

from __future__ import annotations

import json
import math
from datetime import date, timedelta
from pathlib import Path
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

# !! Synthetic data flag — must remain visible !!
SYNTHETIC_DATA = True
SYNTHETIC_DATA_NOTE = (
    "This dataset was generated by synthetic_data.py using hand-crafted "
    "statistical distributions. It does NOT represent real sales data."
)

# Canonical category list — must match category_shelf_life.json keys
CATEGORIES: List[str] = [
    "Dairy",
    "Bakery",
    "Fruits & Veggies",
    "Meat & Seafood",
    "Ready-to-Eat",
    "Beverages",
    "Snacks",
    "Food Grains",
    "Oil & Masala",
    "Frozen",
    "Perfume & Cosmetics",
]

# Kept for backward-compatibility with trainer.py V1 imports
CATEGORY_PERISHABILITY: Dict[str, float] = {
    "Dairy": 1.3,
    "Bakery": 1.2,
    "Fruits & Veggies": 1.4,
    "Meat & Seafood": 1.5,
    "Ready-to-Eat": 1.4,
    "Beverages": 0.8,
    "Snacks": 0.7,
    "Food Grains": 0.4,
    "Oil & Masala": 0.5,
    "Frozen": 0.9,
    "Perfume & Cosmetics": 0.1,
}

# ---------------------------------------------------------------------------
# Internal config loader
# ---------------------------------------------------------------------------
_CONFIG_PATH = Path(__file__).parent / "category_shelf_life.json"


def _load_config() -> Dict[str, Any]:
    with open(_CONFIG_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# Urgency computation (inline, avoids circular import with urgency.py)
# ---------------------------------------------------------------------------
def _compute_urgency_inline(
    days_to_expiry: float,
    cat_config: Dict[str, Any],
) -> float:
    """Compute urgency score from cat_config dict. Mirror of urgency.py logic."""
    shelf_life = float(cat_config["typical_shelf_life_days"])
    clamped_days = max(0.0, min(days_to_expiry, shelf_life))
    curve = cat_config.get("urgency_curve", "sigmoid")
    if curve == "linear_convex":
        power = float(cat_config.get("convex_power", 1.3))
        frac_remaining = clamped_days / shelf_life
        urgency = (1.0 - frac_remaining) ** power
    else:
        steepness = float(cat_config.get("sigmoid_steepness", 10.0))
        inflection_fraction = float(cat_config.get("sigmoid_inflection_fraction", 0.90))
        frac_remaining = clamped_days / shelf_life
        inflection = 1.0 - inflection_fraction
        urgency = 1.0 / (1.0 + math.exp(steepness * (frac_remaining - inflection)))
    return float(max(0.0, min(1.0, urgency)))


# ---------------------------------------------------------------------------
# Sell-probability target: simulates how demand responds to urgency + price
# ---------------------------------------------------------------------------
def _simulate_sell_probability(
    urgency: float,
    current_price: float,
    cost_price: float,
    cat_config: Dict[str, Any],
    temperature: float,
    precip_prob: float,
    is_weekend: bool,
    foot_traffic: float,
    velocity_7d: float,
    rng: np.random.Generator,
) -> float:
    """
    Simulate probability of selling a unit within the remaining expiry window.

    Design decisions:
      - Base elasticity from cold_start_elasticity (category-level price sensitivity).
        Negative means higher price → lower probability. Typical range: -0.4 to -2.2.
      - Urgency boost: near-expiry items get a natural demand boost from discounting
        (if discounted) — encoded here as a urgency-driven base demand signal.
      - Weather: hot temperature boosts fresh/beverages demand; rain suppresses foot traffic.
      - Weekend: higher foot traffic → higher base sell probability.
      - Gaussian noise with σ=0.06 to simulate real-world randomness.
      - All output clipped to [0.01, 0.99].
    """
    elasticity = float(cat_config.get("cold_start_elasticity", -1.0))
    weather_sensitivity = float(cat_config.get("weather_sensitivity", 0.3))
    markdown_ceiling = float(cat_config.get("markdown_ceiling_pct", 50)) / 100.0

    # Base demand from price: log-linear demand model
    # P(sale) ~ exp(elasticity * log(price_ratio)) where price_ratio = current/cost
    margin_ratio = current_price / max(cost_price, 0.01)
    price_effect = math.exp(elasticity * math.log(max(margin_ratio, 0.01)))

    # Urgency-driven demand signal: near-expiry items create discount urgency
    # (simulates manager markdown behaviour pushing demand)
    urgency_demand = 0.3 + 0.7 * urgency  # [0.3 when new, 1.0 when expired]

    # Weather effect on demand (category-specific)
    temp_norm = (temperature - 25.0) / 15.0  # normalised around 25°C
    weather_effect = 1.0 + weather_sensitivity * temp_norm * 0.3
    rain_suppression = 1.0 - weather_sensitivity * precip_prob * 0.2

    # Foot traffic and weekend multiplier
    traffic_effect = 0.5 + 0.5 * foot_traffic  # foot_traffic in [0, 1]
    weekend_boost = 1.15 if is_weekend else 1.0

    # Velocity signal: high recent velocity → existing demand
    velocity_norm = min(1.0, velocity_7d / 20.0)  # normalise around 20 units/day
    velocity_boost = 0.8 + 0.4 * velocity_norm

    # Combine signals multiplicatively
    raw_prob = (
        price_effect
        * urgency_demand
        * weather_effect
        * rain_suppression
        * traffic_effect
        * weekend_boost
        * velocity_boost
    )

    # Normalise to [0.01, 0.99]
    prob = float(np.clip(raw_prob, 0.01, 0.99))

    # Add Gaussian noise (σ=0.06) to simulate real-world randomness
    noise = rng.normal(0.0, 0.06)
    prob = float(np.clip(prob + noise, 0.01, 0.99))

    return prob


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate_synthetic_dataset(
    num_samples: int = 5000,
    random_seed: int = 42,
    start_date: str = "2024-01-01",
    num_stores: int = 6,
    holiday_dates: Optional[List[str]] = None,
) -> pd.DataFrame:
    """
    Generate a synthetic training dataset for the NEXPIRE pricing model.

    !! THIS IS SYNTHETIC DATA — NOT REAL RETAILER DATA !!

    Args:
        num_samples: Number of rows to generate. Default 5000.
        random_seed: Fixed seed for reproducibility. Default 42.
        start_date: ISO date string for the first row's date. Default "2024-01-01".
        num_stores: Number of simulated store IDs to cycle through. Default 6.
        holiday_dates: List of ISO date strings to mark as holidays.
                       Defaults to a small set of Indian public holidays in 2024.

    Returns:
        pd.DataFrame with 16 feature columns + sell_probability target.
        Also sets attribute df.SYNTHETIC_DATA = True on the returned DataFrame.

    Distribution choices (all documented here):
        category:            Uniform across CATEGORIES list.
        days_to_expiry:      Sampled from Uniform(0.1, typical_shelf_life_days).
                             This ensures every batch is within a plausible range.
        current_price:       Uniform(cost_price * 1.05, cost_price * 2.5).
                             Real margins are typically 5–150%; this range is conservative.
        cost_price:          Uniform(5, 500) INR. Covers everything from bread to perfume.
        qty_on_hand:         NegativeBinomial(n=5, p=0.2) — right-skewed; most batches
                             are small (<50 units) with rare large batches.
        avg_daily_velocity:  Exponential(λ=10) units/day — most SKUs sell slowly,
                             few sell very fast.
        temperature_today:   Gaussian(28°C, 5°C), clipped to [15, 45°C].
                             Reflects Indian subcontinent typical range.
        precip_probability:  Beta(1.5, 4) — right-skewed toward dry conditions.
        is_weekend:          Derived from date (Saturday/Sunday).
        is_holiday:          Date lookup against holiday_dates list.
        hour_of_day:         Uniform integer [8, 20] — operating hours.
        store_foot_traffic:  Beta(2, 2) — roughly bell-shaped around 0.5.
        past_discount_depth: Uniform(0, 40%) — historical markdown applied.
        past_sellthrough:    Beta(3, 2) — skewed high (most batches sell through).
        local_demand_score:  Gaussian(0.5, 0.15), clipped to [0, 1].
        b2b_flag:            Bernoulli(0.25) — 25% of batches go to bulk/B2B customers.
    """
    if holiday_dates is None:
        # Default: approximate Indian public holidays in 2024
        holiday_dates = [
            "2024-01-26", "2024-03-25", "2024-04-14", "2024-04-17",
            "2024-08-15", "2024-10-02", "2024-10-12", "2024-11-01",
            "2024-11-15", "2024-12-25",
        ]
    holiday_set = set(holiday_dates)

    rng = np.random.default_rng(random_seed)
    config = _load_config()
    cat_configs = config["categories"]
    default_cfg = config["_default_fallback"]

    start = date.fromisoformat(start_date)
    rows = []

    for i in range(num_samples):
        # --- Date (spread evenly across ~1 year) ---
        row_date = start + timedelta(days=int(i * 365 / num_samples))
        date_str = row_date.isoformat()
        is_weekend = row_date.weekday() >= 5  # Saturday=5, Sunday=6
        is_holiday = date_str in holiday_set

        # --- Category ---
        # Uniform draw across all categories so every category has enough data
        category = rng.choice(CATEGORIES)
        cfg = cat_configs.get(category, default_cfg)
        shelf_life = float(cfg["typical_shelf_life_days"])
        weather_sens = float(cfg.get("weather_sensitivity", 0.2))

        # --- Store ---
        store_id = int(rng.integers(1, num_stores + 1))
        sku_id = f"{category[:3].upper()}-{i:05d}"

        # --- Time features ---
        days_to_expiry = float(rng.uniform(0.1, shelf_life))
        hour_of_day = int(rng.integers(8, 21))

        # --- Price features ---
        # Cost price: wider range for non-perishables (perfume vs. bread)
        if cfg.get("urgency_curve") == "sigmoid" and shelf_life > 100:
            cost_price = round(float(rng.uniform(20.0, 500.0)), 2)
        else:
            cost_price = round(float(rng.uniform(5.0, 150.0)), 2)
        # Current price: 5% to 250% margin over cost
        price_multiplier = rng.uniform(1.05, 2.5)
        current_price = round(float(cost_price * price_multiplier), 2)

        # --- Inventory features ---
        # NegativeBinomial(n=5, p=0.2): mean=20, right-skewed
        qty_on_hand = int(rng.negative_binomial(5, 0.2) + 1)

        # Velocity: Exponential(λ=10). Most SKUs sell 0–15 units/day.
        avg_daily_velocity_7d = round(float(rng.exponential(10.0)), 2)
        # 28d velocity has lower variance (averaged over longer window)
        avg_daily_velocity_28d = round(float(
            avg_daily_velocity_7d * rng.uniform(0.7, 1.3)
        ), 2)

        # --- Weather ---
        # Indian subcontinent: mean 28°C, σ=5, clipped [15, 45]
        temperature_today = round(float(np.clip(rng.normal(28.0, 5.0), 15.0, 45.0)), 1)
        # Precip: Beta(1.5, 4) — mostly dry with occasional high-precip events
        precip_probability = round(float(rng.beta(1.5, 4.0)), 3)

        # --- Context features ---
        # Foot traffic: Beta(2, 2) bell-shaped around 0.5
        store_foot_traffic_index = round(float(rng.beta(2.0, 2.0)), 3)
        # Historical discount depth: Uniform(0, 40%)
        past_discount_depth = round(float(rng.uniform(0.0, 40.0)), 2)
        # Historical sell-through: Beta(3, 2) — most items sell through
        past_sellthrough_rate = round(float(rng.beta(3.0, 2.0)), 3)
        # Local demand: Gaussian(0.5, 0.15) clipped [0, 1]
        local_demand_score = round(float(np.clip(rng.normal(0.5, 0.15), 0.0, 1.0)), 3)
        # B2B flag: 25% of batches go to bulk/institutional buyers
        b2b_flag = int(rng.random() < 0.25)

        # --- Engineered features ---
        urgency_score = _compute_urgency_inline(days_to_expiry, cfg)
        # Category × weather interaction features
        # Encode as: weather_sensitivity × normalised temperature (or precip)
        temp_norm = (temperature_today - 25.0) / 20.0  # range approx [-0.5, 1.0]
        cat_x_temp = round(float(weather_sens * temp_norm), 4)
        cat_x_precip = round(float(weather_sens * precip_probability), 4)

        # --- Target: sell probability ---
        sell_prob = _simulate_sell_probability(
            urgency=urgency_score,
            current_price=current_price,
            cost_price=cost_price,
            cat_config=cfg,
            temperature=temperature_today,
            precip_prob=precip_probability,
            is_weekend=is_weekend,
            foot_traffic=store_foot_traffic_index,
            velocity_7d=avg_daily_velocity_7d,
            rng=rng,
        )

        rows.append({
            "date": date_str,
            "sku_id": sku_id,
            "store_id": store_id,
            "category": category,
            # Raw time signal — kept for audit but NOT fed to model
            "days_to_expiry": round(days_to_expiry, 2),
            # Normalised urgency — THIS replaces days_to_expiry in the model
            "urgency_score": round(urgency_score, 4),
            "current_price": current_price,
            "cost_price": cost_price,
            "qty_on_hand": qty_on_hand,
            "avg_daily_velocity_7d": avg_daily_velocity_7d,
            "avg_daily_velocity_28d": avg_daily_velocity_28d,
            "temperature_today": temperature_today,
            "precip_probability": precip_probability,
            "is_weekend": int(is_weekend),
            "is_holiday": int(is_holiday),
            "hour_of_day": hour_of_day,
            "store_foot_traffic_index": store_foot_traffic_index,
            "past_discount_depth": past_discount_depth,
            "past_sellthrough_rate": past_sellthrough_rate,
            "local_demand_score": local_demand_score,
            "b2b_flag": b2b_flag,
            "cat_x_temp": cat_x_temp,
            "cat_x_precip": cat_x_precip,
            # TARGET
            "sell_probability": round(sell_prob, 4),
        })

    df = pd.DataFrame(rows)
    df["date"] = pd.to_datetime(df["date"])
    df.sort_values("date", inplace=True)
    df.reset_index(drop=True, inplace=True)

    # Attach metadata attribute (for callers that want to verify)
    df.attrs["SYNTHETIC_DATA"] = True
    df.attrs["note"] = SYNTHETIC_DATA_NOTE

    return df


if __name__ == "__main__":
    import sys
    print("Generating 5,000-row synthetic dataset...")
    df = generate_synthetic_dataset(num_samples=5000)
    out_path = Path(__file__).parent / "artifacts" / "synthetic_dataset.csv"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)
    print(f"Saved to {out_path}")
    print(df.describe())
    print(f"\nColumns: {list(df.columns)}")
    print(f"\n!! SYNTHETIC DATA — NOT REAL: {SYNTHETIC_DATA_NOTE}")
